---
- name: Test filter plugin
  hosts: all
  user: jparrill
  tasks:
  ## This task will create this fact: gi_management_interface
  - name: 'Set Management interface based on a regex'
    get_interface:
      topic: 'management'
      regex: '192.168'

  - name: debug
    debug: msg="management interface {{ gi_management_interface }}"
